services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-network

  postgres-container:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meeting_room_booking_system
      POSTGRES_USER: wangjian
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - common-network

  redis-container:
    image: redis
    volumes:
      - ./redis-data:/data
    networks:
      - common-network
      
networks:
  common-network:
    driver: bridge
