###
// 注册
POST http://127.0.0.1:3000/user/register HTTP/1.1
content-type: application/json

{
		"username": "test",
		"password": "test123456"
}

###
// 登录
POST http://127.0.0.1:3000/user/login HTTP/1.1
content-type: application/json

{
		"username": "test",
		"password": "test123456"
}
