@baseUrl = http://127.0.0.1:3000

###
GET {{baseUrl}}/user/init HTTP/1.1

###
GET {{baseUrl}}/user/captcha?address=928647866@qq.com HTTP/1.1

###
POST {{baseUrl}}/user/register HTTP/1.1
content-type: application/json

{
		"username": "test",
		"password": "test123456",
		"nickName": "test",
		"email": "928647866@qq.com",
		"captcha": "209440"
}

###
# @name login
POST {{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
		"username": "lisi",
		"password": "222222"
}

### 

@authToken = {{login.response.body.data.accessToken}}

###
GET {{baseUrl}}/bbb HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoibGlzaSIsInJvbGVzIjpbIuaZrumAmueUqOaItyJdLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsImNvZGUiOiJjY2MiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBjY2Mg5o6l5Y-jIn1dLCJpYXQiOjE3MjI0OTg5NTQsImV4cCI6MTcyMjUwMDc1NH0.C3Jy3qyGh0XcVYfYKPyn2WMjf0VgG_b_MJqEESHk9IA
content-type: application/json

###
GET {{baseUrl}}/user/info HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoibGlzaSIsInJvbGVzIjpbIuaZrumAmueUqOaItyJdLCJwZXJtaXNzaW9ucyI6W3siaWQiOjEsImNvZGUiOiJjY2MiLCJkZXNjcmlwdGlvbiI6Iuiuv-mXriBjY2Mg5o6l5Y-jIn1dLCJpYXQiOjE3MjI0OTg5NTQsImV4cCI6MTcyMjUwMDc1NH0.C3Jy3qyGh0XcVYfYKPyn2WMjf0VgG_b_MJqEESHk9IA
content-type: application/json

###
# @name admin
POST {{baseUrl}}/user/admin/login HTTP/1.1
content-type: application/json

{
		"username": "zhangsan",
		"password": "111111"
}

### 
@adminAuthToken = {{admin.response.body.accessToken}}

###
GET {{baseUrl}}/aaa HTTP/1.1
Authorization: Bearer {{adminAuthToken}}
content-type: application/json

###
GET {{baseUrl}}/book HTTP/1.1
content-type: application/json


###
POST {{baseUrl}}/book HTTP/1.1
content-type: application/json

{
		"name": "红楼梦",
		"author": "曹雪芹",
		"description": "中国古代四大名著之一",
		"cover": "xx.png"
}


###
GET {{baseUrl}}/book/384730 HTTP/1.1
content-type: application/json


###
PATCH {{baseUrl}}/book HTTP/1.1
content-type: application/json

{
		"id": 384730,
		"name": "红楼梦2",
		"author": "曹雪芹2",
		"description": "中国古代四大名著之一",
		"cover": "xx1.png"
}


###
DELETE {{baseUrl}}/book/384730 HTTP/1.1
content-type: application/json

